[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999

# CRT
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.SHADERS['CRT']:send('glitch_intensity', 0)--0.1*G.SETTINGS.GRAPHICS.crt/100 + (G.screenwipe_amt) + 1)"
position = "at"
payload = '''
G.SHADERS['CRT']:send('glitch_intensity', BadDirector_get_crt_vals('glitch') or 0)
G.SHADERS['CRT']:send('noise_fac', BadDirector_get_crt_vals('noise') or 0)
G.SHADERS['CRT']:send('crt_intensity', BadDirector_get_crt_vals('intensity') or 0)
'''
match_indent = true


# Cryptid compatibility
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.SHADERS['CRT']:send('glitch_intensity', glitched_intensity or 0)"
position = "at"
payload = '''
G.SHADERS['CRT']:send('glitch_intensity', BadDirector_get_crt_vals('glitch') or 0)
G.SHADERS['CRT']:send('noise_fac', BadDirector_get_crt_vals('noise') or 0)
G.SHADERS['CRT']:send('crt_intensity', BadDirector_get_crt_vals('intensity') or 0)
'''
match_indent = true
