[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
if card.config.center.set == 'Tarot' or card.config.center.set == 'Planet' then 
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.last_tarot_planet = card.config.center_key
            return true
        end
      }))
        return true
    end
  }))
end
'''
position = "after"
payload = '''
if card.config.center.set == 'misplanet' or 
card.config.center.set == 'mistarot' then 
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.last_tarot_planet = card.config.center.key
            return true
        end
      }))
        return true
    end
  }))
end

if card.ability.consumeable then 
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.bd_last_used_cons = card.config.center.key
            return true
        end
      }))
        return true
    end
  }))
end
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
if e.config.id == 'buy_and_use' then 
  G.FUNCS.use_card(e, true)
'''
position = "after"
payload = '''
if c1.ability.consumeable then
  G.GAME.bd_last_consumeable_added = c1.config.center.key
  G.GAME.bd_last_card_added = c1.config.center.key
end
'''
match_indent = true

